### ISSUE TITLE
Support latest rzk versions

### ISSUE THREAD

**Issue by fizruk** [rzk-lang/mkdocs-plugin-rzk#3]
Apparently something has changed in the recent versions, and this plugin can no longer properly generate SVGs. For instance, there is nothing on this page in `rzk` documentation: https://rzk-lang.github.io/rzk/v0.6.7/reference/render.rzk/

**Comment by aabounegm** [comment]
The reason is that running `rzk typecheck` (without any parameters) used to accept the input from `stdin`, but this was changed in `v0.6.5` to instead use `rzk.yaml`. I am working on a fix now
